// Cards Against Humanity Card Database
// 100 Black Cards (prompts) + 400 White Cards (answers)

export const BLACK_CARDS = [
    { id: 1, text: "What's that smell?", pick: 1 },
    { id: 2, text: "I got 99 problems but ___ ain't one.", pick: 1 },
    { id: 3, text: "What's the next Happy Meal toy?", pick: 1 },
    { id: 4, text: "It's a pity that kids these days are all getting involved with ___.", pick: 1 },
    { id: 5, text: "What ended my last relationship?", pick: 1 },
    { id: 6, text: "MTV's new reality show features eight washed-up celebrities living with ___.", pick: 1 },
    { id: 7, text: "I drink to forget ___.", pick: 1 },
    { id: 8, text: "I'm sorry, Professor, but I couldn't complete my homework because of ___.", pick: 1 },
    { id: 9, text: "Alternative medicine is now embracing the curative powers of ___.", pick: 1 },
    { id: 10, text: "What's my secret power?", pick: 1 },
    { id: 11, text: "What gives me uncontrollable gas?", pick: 1 },
    { id: 12, text: "What will always get you laid?", pick: 1 },
    { id: 13, text: "What would grandma find disturbing, yet oddly charming?", pick: 1 },
    { id: 14, text: "What's there a ton of in heaven?", pick: 1 },
    { id: 15, text: "During his midlife crisis, my dad got really into ___.", pick: 1 },
    { id: 16, text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate ___.", pick: 1 },
    { id: 17, text: "What did I bring back from Mexico?", pick: 1 },
    { id: 18, text: "Next from J.K. Rowling: Harry Potter and the Chamber of ___.", pick: 1 },
    { id: 19, text: "A romantic candlelit dinner would be incomplete without ___.", pick: 1 },
    { id: 20, text: "White people like ___.", pick: 1 },
    { id: 21, text: "___. Betcha can't have just one!", pick: 1 },
    { id: 22, text: "What's the most emo?", pick: 1 },
    { id: 23, text: "___ + ___ = ___", pick: 3 },
    { id: 24, text: "What never fails to liven up the party?", pick: 1 },
    { id: 25, text: "War! What is it good for?", pick: 1 },
    { id: 26, text: "In M. Night Shyamalan's new movie, Bruce Willis discovers that ___ had really been ___ all along.", pick: 2 },
    { id: 27, text: "What's my anti-drug?", pick: 1 },
    { id: 28, text: "When Pharaoh remained unmoved, Moses called down a Plague of ___.", pick: 1 },
    { id: 29, text: "Maybe she's born with it. Maybe it's ___.", pick: 1 },
    { id: 30, text: "What am I giving up for Lent?", pick: 1 },
    { id: 31, text: "What do old people smell like?", pick: 1 },
    { id: 32, text: "This is the way the world ends / This is the way the world ends / Not with a bang but with ___.", pick: 1 },
    { id: 33, text: "What is Batman's guilty pleasure?", pick: 1 },
    { id: 34, text: "TSA guidelines now prohibit ___ on airplanes.", pick: 1 },
    { id: 35, text: "In 1,000 years, when paper money is but a distant memory, how will we pay for goods and services?", pick: 1 },
    { id: 36, text: "Instead of coal, Santa now gives bad children ___.", pick: 1 },
    { id: 37, text: "Step 1: ___. Step 2: ___. Step 3: Profit.", pick: 2 },
    { id: 38, text: "Coming to Broadway this season, ___: The Musical.", pick: 1 },
    { id: 39, text: "What helps Obama unwind?", pick: 1 },
    { id: 40, text: "What's the crustiest?", pick: 1 },
    { id: 41, text: "What did the US airdrop to the children of Afghanistan?", pick: 1 },
    { id: 42, text: "Why can't I sleep at night?", pick: 1 },
    { id: 43, text: "What will I bring back in time to convince people that I am a powerful wizard?", pick: 1 },
    { id: 44, text: "When I was tripping on acid, ___ turned into ___.", pick: 2 },
    { id: 45, text: "How am I maintaining my relationship status?", pick: 1 },
    { id: 46, text: "Life for American Indians was forever changed when the White Man introduced them to ___.", pick: 1 },
    { id: 47, text: "Science will never explain ___.", pick: 1 },
    { id: 48, text: "What are my parents hiding from me?", pick: 1 },
    { id: 49, text: "Why am I sticky?", pick: 1 },
    { id: 50, text: "What's the next superhero/porn star crossover?", pick: 1 },
    { id: 51, text: "Studies show that lab rats navigate mazes 50% faster after being exposed to ___.", pick: 1 },
    { id: 52, text: "I never truly understood ___ until I encountered ___.", pick: 2 },
    { id: 53, text: "In a world ravaged by ___, our only solace is ___.", pick: 2 },
    { id: 54, text: "That's right, I killed ___. How, you ask? ___.", pick: 2 },
    { id: 55, text: "I learned the hard way that you can't own ___ without also owning ___.", pick: 2 },
    { id: 56, text: "Before I run for president, I must destroy all evidence of my involvement with ___.", pick: 1 },
    { id: 57, text: "What's Teach for America using to inspire inner city students to succeed?", pick: 1 },
    { id: 58, text: "Next on ESPN2: The World Series of ___.", pick: 1 },
    { id: 59, text: "When I pooped, what came out of my butt?", pick: 1 },
    { id: 60, text: "What has been making life difficult at the nudist colony?", pick: 1 },
    { id: 61, text: "___ is a slippery slope that leads to ___.", pick: 2 },
    { id: 62, text: "In his new self-produced album, Kanye West raps over the sounds of ___.", pick: 1 },
    { id: 63, text: "After months of practice with ___, I think I'm finally ready for ___.", pick: 2 },
    { id: 64, text: "Dear Abby, I'm having some trouble with ___ and would like your advice.", pick: 1 },
    { id: 65, text: "During sex, I like to think about ___.", pick: 1 },
    { id: 66, text: "The CIA now interrogates enemy agents by repeatedly subjecting them to ___.", pick: 1 },
    { id: 67, text: "My country, 'tis of thee, sweet land of ___.", pick: 1 },
    { id: 68, text: "And the Academy Award for ___ goes to ___.", pick: 2 },
    { id: 69, text: "In Michael Jackson's final moments, he thought about ___.", pick: 1 },
    { id: 70, text: "What's the new fad diet?", pick: 1 },
    { id: 71, text: "After the earthquake, Sean Penn brought ___ to the people of Haiti.", pick: 1 },
    { id: 72, text: "Why do I hurt all over?", pick: 1 },
    { id: 73, text: "Lifetime presents ___, the story of ___.", pick: 2 },
    { id: 74, text: "Make a haiku.", pick: 3 },
    { id: 75, text: "What's my secret ingredient?", pick: 1 },
    { id: 76, text: "What gives me gag reflexes?", pick: 1 },
    { id: 77, text: "I got 99 problems but ___ ain't one.", pick: 1 },
    { id: 78, text: "Fun tip! When your man asks you to go down on him, try surprising him with ___ instead.", pick: 1 },
    { id: 79, text: "The class field trip was completely ruined by ___.", pick: 1 },
    { id: 80, text: "How did I lose my virginity?", pick: 1 },
    { id: 81, text: "What's George Bush thinking about right now?", pick: 1 },
    { id: 82, text: "If God didn't want us to enjoy ___, he wouldn't have given us ___.", pick: 2 },
    { id: 83, text: "But before I kill you, Mr. Bond, I must show you ___.", pick: 1 },
    { id: 84, text: "What does Dick Cheney prefer?", pick: 1 },
    { id: 85, text: "What's the gift that keeps on giving?", pick: 1 },
    { id: 86, text: "Major League Baseball has banned ___ for giving players an unfair advantage.", pick: 1 },
    { id: 87, text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ___.", pick: 1 },
    { id: 88, text: "Why am I broke?", pick: 1 },
    { id: 89, text: "Dude, do not go in that bathroom. There's ___ in there.", pick: 1 },
    { id: 90, text: "You haven't truly lived until you've experienced ___ and ___ at the same time.", pick: 2 },
    { id: 91, text: "Tonight on 20/20: What you don't know about ___ could kill you.", pick: 1 },
    { id: 92, text: "How did you celebrate your 21st birthday?", pick: 1 },
    { id: 93, text: "What's the worst thing that ever happened to you?", pick: 1 },
    { id: 94, text: "What do you think about when you masturbate?", pick: 1 },
    { id: 95, text: "In the distant future, historians will agree that ___ marked the beginning of America's decline.", pick: 1 },
    { id: 96, text: "What would you put in room 101 to break Winston?", pick: 1 },
    { id: 97, text: "The Smithsonian Museum of Natural History has just opened an exhibit on ___.", pick: 1 },
    { id: 98, text: "What ruined Thanksgiving this year?", pick: 1 },
    { id: 99, text: "Why can't we have nice things?", pick: 1 },
    { id: 100, text: "Introducing X-treme Baseball! It's like baseball but with ___!", pick: 1 }
];

export const WHITE_CARDS = [
    { id: 1, text: "A disappointing birthday party" },
    { id: 2, text: "Grandma's secret ingredient" },
    { id: 3, text: "Praying the gay away" },
    { id: 4, text: "Two midgets shitting in a bucket" },
    { id: 5, text: "Darth Vader" },
    { id: 6, text: "Rushing" },
    { id: 7, text: "Being a dick to children" },
    { id: 8, text: "My sex life" },
    { id: 9, text: "Cheating in the Special Olympics" },
    { id: 10, text: "Swooping" },
    { id: 11, text: "Finger painting" },
    { id: 12, text: "Self-loathing" },
    { id: 13, text: "A good sniff" },
    { id: 14, text: "Coat hanger abortions" },
    { id: 15, text: "Soup that is too hot" },
    { id: 16, text: "Man meat" },
    { id: 17, text: "Bingeing and purging" },
    { id: 18, text: "Dying" },
    { id: 19, text: "Passing gas" },
    { id: 20, text: "Autocannibalism" },
    { id: 21, text: "The Dance of the Sugar Plum Fairy" },
    { id: 22, text: "Nazis" },
    { id: 23, text: "A bleached asshole" },
    { id: 24, text: "German dungeon porn" },
    { id: 25, text: "Licking things to claim them as your own" },
    { id: 26, text: "Mutually-assured destruction" },
    { id: 27, text: "Shapeshifters" },
    { id: 28, text: "A moment of silence" },
    { id: 29, text: "The American Dream" },
    { id: 30, text: "Sunshine and rainbows" },
    { id: 31, text: "Erectile dysfunction" },
    { id: 32, text: "Edible underpants" },
    { id: 33, text: "Vigorous jazz hands" },
    { id: 34, text: "Roofies" },
    { id: 35, text: "Pictures of boobs" },
    { id: 36, text: "Dead parents" },
    { id: 37, text: "A windmill full of corpses" },
    { id: 38, text: "Oompa-Loompas" },
    { id: 39, text: "A cooler full of organs" },
    { id: 40, text: "Getting naked and watching Nickelodeon" },
    { id: 41, text: "Hot cheese" },
    { id: 42, text: "The Three-Fifths compromise" },
    { id: 43, text: "Saxophone solos" },
    { id: 44, text: "A gypsy curse" },
    { id: 45, text: "Frolicking" },
    { id: 46, text: "Unfathomable stupidity" },
    { id: 47, text: "Horrifying laser hair removal accidents" },
    { id: 48, text: "Goblins" },
    { id: 49, text: "Exactly what you'd expect" },
    { id: 50, text: "Inappropriate yodeling" },
    { id: 51, text: "Natural selection" },
    { id: 52, text: "Stranger danger" },
    { id: 53, text: "Consultants" },
    { id: 54, text: "Getting really high" },
    { id: 55, text: "Chivalry" },
    { id: 56, text: "Her Majesty, Queen Elizabeth II" },
    { id: 57, text: "Ronald Reagan" },
    { id: 58, text: "The placenta" },
    { id: 59, text: "The Rev. Dr. Martin Luther King, Jr." },
    { id: 60, text: "Raping and pillaging" },
    { id: 61, text: "The forbidden fruit" },
    { id: 62, text: "Agriculture" },
    { id: 63, text: "Flightless birds" },
    { id: 64, text: "Chutzpah" },
    { id: 65, text: "BATMAN!!!" },
    { id: 66, text: "A sad handjob" },
    { id: 67, text: "Sexting" },
    { id: 68, text: "Balls" },
    { id: 69, text: "Spectacular abs" },
    { id: 70, text: "My collection of high-tech sex toys" },
    { id: 71, text: "Harry Potter erotica" },
    { id: 72, text: "Explosive decompression" },
    { id: 73, text: "Full frontal nudity" },
    { id: 74, text: "A sassy black woman" },
    { id: 75, text: "Geese" },
    { id: 76, text: "Necrophilia" },
    { id: 77, text: "Boogers" },
    { id: 78, text: "Kamikaze pilots" },
    { id: 79, text: "A homoerotic volleyball montage" },
    { id: 80, text: "The terrorists" },
    { id: 81, text: "The token minority" },
    { id: 82, text: "A foul mouth" },
    { id: 83, text: "Testicular torsion" },
    { id: 84, text: "Eating all of the cookies before the AIDS bake-sale" },
    { id: 85, text: "Attitude" },
    { id: 86, text: "Waking up half-naked in a Denny's parking lot" },
    { id: 87, text: "A big hoopla about nothing" },
    { id: 88, text: "All-you-can-eat shrimp for $4.99" },
    { id: 89, text: "My genitals" },
    { id: 90, text: "Free samples" },
    { id: 91, text: "Active listening" },
    { id: 92, text: "Sharing needles" },
    { id: 93, text: "Genital piercings" },
    { id: 94, text: "The hardworking Mexican" },
    { id: 95, text: "Teenage pregnancy" },
    { id: 96, text: "Poorly-timed Holocaust jokes" },
    { id: 97, text: "My relationship status" },
    { id: 98, text: "Doing the right thing" },
    { id: 99, text: "My inner demons" },
    { id: 100, text: "Heteronormativity" },
    { id: 101, text: "Being fabulous" },
    { id: 102, text: "The violation of our most basic human rights" },
    { id: 103, text: "Smallpox blankets" },
    { id: 104, text: "Home video of Oprah sobbing into a Lean Cuisine" },
    { id: 105, text: "Half-assed foreplay" },
    { id: 106, text: "Wifely duties" },
    { id: 107, text: "A really cool hat" },
    { id: 108, text: "Chainsaws for hands" },
    { id: 109, text: "Destroying the evidence" },
    { id: 110, text: "Whipping it out" },
    { id: 111, text: "Letting yourself go" },
    { id: 112, text: "Being marginalized" },
    { id: 113, text: "Lactation" },
    { id: 114, text: "Jewish fraternities" },
    { id: 115, text: "Emotions" },
    { id: 116, text: "Famine" },
    { id: 117, text: "A robust mongoloid" },
    { id: 118, text: "Chunks of dead hitchhiker" },
    { id: 119, text: "A falcon with a cap on its head" },
    { id: 120, text: "Sperm whales" },
    { id: 121, text: "Booby-trapping the house to foil burglars" },
    { id: 122, text: "The inevitable heat death of the universe" },
    { id: 123, text: "A bitch slap" },
    { id: 124, text: "The World of Warcraft" },
    { id: 125, text: "Crippling debt" },
    { id: 126, text: "Vikings" },
    { id: 127, text: "Sean Penn" },
    { id: 128, text: "Children on leashes" },
    { id: 129, text: "A murder most foul" },
    { id: 130, text: "Finding a skeleton" },
    { id: 131, text: "Being awesome at sex" },
    { id: 132, text: "The Jews" },
    { id: 133, text: "A Super Soaker™ full of cat pee" },
    { id: 134, text: "A stray pube" },
    { id: 135, text: "Public ridicule" },
    { id: 136, text: "Parting the Red Sea" },
    { id: 137, text: "Picking up girls at the abortion clinic" },
    { id: 138, text: "Me time" },
    { id: 139, text: "Hormone injections" },
    { id: 140, text: "A lifetime of sadness" },
    { id: 141, text: "AIDS" },
    { id: 142, text: "Making sex at her" },
    { id: 143, text: "Feeding Rosie O'Donnell" },
    { id: 144, text: "MechaHitler" },
    { id: 145, text: "Not giving a shit about the Third World" },
    { id: 146, text: "Puberty" },
    { id: 147, text: "Sniffing glue" },
    { id: 148, text: "Amputees" },
    { id: 149, text: "Multiple stab wounds" },
    { id: 150, text: "A mopey zoo lion" },
    { id: 151, text: "Farting and walking away" },
    { id: 152, text: "Switching to Geico" },
    { id: 153, text: "72 virgins" },
    { id: 154, text: "Masturbation" },
    { id: 155, text: "The clitoris" },
    { id: 156, text: "Too much hair gel" },
    { id: 157, text: "Object permanence" },
    { id: 158, text: "Classist undertones" },
    { id: 159, text: "Powerful thighs" },
    { id: 160, text: "Uppercuts" },
    { id: 161, text: "Flesh-eating bacteria" },
    { id: 162, text: "Racially-biased SAT questions" },
    { id: 163, text: "A monkey smoking a cigar" },
    { id: 164, text: "Sexual tension" },
    { id: 165, text: "A balanced breakfast" },
    { id: 166, text: "Raptor attacks" },
    { id: 167, text: "Overcompensation" },
    { id: 168, text: "Crippling debt" },
    { id: 169, text: "Dropping a chandelier on your enemies and riding the rope up" },
    { id: 170, text: "Black people" },
    { id: 171, text: "Clowns" },
    { id: 172, text: "Chekhov's gun" },
    { id: 173, text: "Queefing" },
    { id: 174, text: "White privilege" },
    { id: 175, text: "Teaching a robot to love" },
    { id: 176, text: "Ethnic cleansing" },
    { id: 177, text: "Getting married, having a few kids, buying some stuff, retiring to Florida, and dying" },
    { id: 178, text: "Ghosts" },
    { id: 179, text: "A falcon with a cap on its head" },
    { id: 180, text: "Apologizing" },
    { id: 181, text: "Peeing a little bit" },
    { id: 182, text: "Heartwarming orphans" },
    { id: 183, text: "An erection that lasts more than four hours" },
    { id: 184, text: "Mouth herpes" },
    { id: 185, text: "A drive-by shooting" },
    { id: 186, text: "Skeletons" },
    { id: 187, text: "Pandora's vagina" },
    { id: 188, text: "Taking off your shirt" },
    { id: 189, text: "Catapults" },
    { id: 190, text: "The gays" },
    { id: 191, text: "Glenn Beck being harried by a swarm of buzzards" },
    { id: 192, text: "The chronic" },
    { id: 193, text: "Authentic Mexican cuisine" },
    { id: 194, text: "Morgan Freeman's voice" },
    { id: 195, text: "A defective condom" },
    { id: 196, text: "One trillion dollars" },
    { id: 197, text: "Sexism" },
    { id: 198, text: "Puppies!" },
    { id: 199, text: "My vagina" },
    { id: 200, text: "Old-people smell" },
    { id: 201, text: "A good, strong gorilla" },
    { id: 202, text: "Glenn Beck catching his scrotum on a curtain hook" },
    { id: 203, text: "Children with ass cancer" },
    { id: 204, text: "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts" },
    { id: 205, text: "Concealing a boner" },
    { id: 206, text: "Menstruation" },
    { id: 207, text: "Pooping back and forth. Forever." },
    { id: 208, text: "Cuddling" },
    { id: 209, text: "Civilian casualties" },
    { id: 210, text: "My machete" },
    { id: 211, text: "A bucket of fish heads" },
    { id: 212, text: "Anal beads" },
    { id: 213, text: "The South" },
    { id: 214, text: "A salty surprise" },
    { id: 215, text: "Britney Spears at 55" },
    { id: 216, text: "Silence" },
    { id: 217, text: "Yeast" },
    { id: 218, text: "Leprosy" },
    { id: 219, text: "Guys who don't call" },
    { id: 220, text: "Getting drunk on mouthwash" },
    { id: 221, text: "Not reciprocating oral sex" },
    { id: 222, text: "A LARPing accident" },
    { id: 223, text: "Panda sex" },
    { id: 224, text: "The invisible hand" },
    { id: 225, text: "The Hustle" },
    { id: 226, text: "Friction" },
    { id: 227, text: "A micropenis" },
    { id: 228, text: "Pixelated bukkake" },
    { id: 229, text: "Twinkies" },
    { id: 230, text: "Spamming" },
    { id: 231, text: "A sad fat dragon with no friends" },
    { id: 232, text: "Riding off into the sunset" },
    { id: 233, text: "Lance Armstrong's missing testicle" },
    { id: 234, text: "Tangled Slinkys" },
    { id: 235, text: "Waking up in a pool of blood" },
    { id: 236, text: "Sweet, sweet vengeance" },
    { id: 237, text: "Rush Limbaugh's soft, shitty body" },
    { id: 238, text: "Raptor attacks" },
    { id: 239, text: "Tentacle porn" },
    { id: 240, text: "Passive-aggressive Post-it notes" },
    { id: 241, text: "Breaking out into song and dance" },
    { id: 242, text: "Vigilante justice" },
    { id: 243, text: "Peeing in a boner" },
    { id: 244, text: "The true meaning of Christmas" },
    { id: 245, text: "Eugenics" },
    { id: 246, text: "A mating display" },
    { id: 247, text: "Wiping her butt" },
    { id: 248, text: "A gentle caress of the inner thigh" },
    { id: 249, text: "The penny whistle solo from 'My Heart Will Go On'" },
    { id: 250, text: "A fart" },
    { id: 251, text: "An M. Night Shyamalan plot twist" },
    { id: 252, text: "The KKK" },
    { id: 253, text: "AXE Body Spray" },
    { id: 254, text: "Pretending to care" },
    { id: 255, text: "A middle-aged man on roller skates" },
    { id: 256, text: "Repression" },
    { id: 257, text: "Police brutality" },
    { id: 258, text: "Nickelback" },
    { id: 259, text: "Throwing a virgin into a volcano" },
    { id: 260, text: "An Oedipus complex" },
    { id: 261, text: "The Holy Bible" },
    { id: 262, text: "Spontaneous human combustion" },
    { id: 263, text: "A falcon with a cap on its head" },
    { id: 264, text: "A lifetime of regret" },
    { id: 265, text: "Aaron Burr" },
    { id: 266, text: "Firing a rifle into the air while balls deep in a squealing hog" },
    { id: 267, text: "My humps" },
    { id: 268, text: "A gassy antelope" },
    { id: 269, text: "Child abuse" },
    { id: 270, text: "Dark and mysterious forces beyond our control" },
    { id: 271, text: "Michael Jackson" },
    { id: 272, text: "A sausage festival" },
    { id: 273, text: "A thermonuclear detonation" },
    { id: 274, text: "The Big Bang" },
    { id: 275, text: "Girls that always be texting" },
    { id: 276, text: "Arnold Schwarzenegger" },
    { id: 277, text: "Toni Morrison's vagina" },
    { id: 278, text: "Stranger danger" },
    { id: 279, text: "Expecting a burp and vomiting on the floor" },
    { id: 280, text: "A beached whale" },
    { id: 281, text: "A windmill full of corpses" },
    { id: 282, text: "Waterboarding" },
    { id: 283, text: "A drive-by shooting" },
    { id: 284, text: "Drinking alone" },
    { id: 285, text: "Viagra" },
    { id: 286, text: "Vehicular manslaughter" },
    { id: 287, text: "Being on fire" },
    { id: 288, text: "Lunchables" },
    { id: 289, text: "Soiling oneself" },
    { id: 290, text: "Oprah sobbing into a Lean Cuisine" },
    { id: 291, text: "The blood of Christ" },
    { id: 292, text: "Spontaneous human combustion" },
    { id: 293, text: "Muhammad (Praise Be Unto Him)" },
    { id: 294, text: "Actually taking candy from a baby" },
    { id: 295, text: "Racially-sensitive termite exterminators" },
    { id: 296, text: "Crystal meth" },
    { id: 297, text: "Italians" },
    { id: 298, text: "Another goddamn vampire movie" },
    { id: 299, text: "Surprise sex!" },
    { id: 300, text: "Copping a feel" },
    { id: 301, text: "Preteens" },
    { id: 302, text: "Dick fingers" },
    { id: 303, text: "Obesity" },
    { id: 304, text: "When you fart and a little bit comes out" },
    { id: 305, text: "Fancy Feast" },
    { id: 306, text: "Dropping a chandelier on your enemies and riding the rope up" },
    { id: 307, text: "Scrotum tickling" },
    { id: 308, text: "John Wilkes Booth" },
    { id: 309, text: "A Gypsy curse" },
    { id: 310, text: "The violation of our most basic human rights" },
    { id: 311, text: "Soup that is too hot" },
    { id: 312, text: "That thing that electrocutes your abs" },
    { id: 313, text: "A zesty breakfast burrito" },
    { id: 314, text: "A mime having a stroke" },
    { id: 315, text: "Dwarf tossing" },
    { id: 316, text: "Dry heaving" },
    { id: 317, text: "The gnhg sound of Chewbacca's bowcaster" },
    { id: 318, text: "Tasteful sideboob" },
    { id: 319, text: "Foreskin" },
    { id: 320, text: "Gandalf" },
    { id: 321, text: "The Rapture" },
    { id: 322, text: "Donald Trump" },
    { id: 323, text: "Diabetes" },
    { id: 324, text: "Kanye West" },
    { id: 325, text: "My mom's rape whistle" },
    { id: 326, text: "Barack Obama" },
    { id: 327, text: "The profoundly handicapped" },
    { id: 328, text: "My anus" },
    { id: 329, text: "Fingering" },
    { id: 330, text: "Pabst Blue Ribbon" },
    { id: 331, text: "Incest" },
    { id: 332, text: "Shaquille O'Neal's acting career" },
    { id: 333, text: "The Underground Railroad" },
    { id: 334, text: "Leveling a city to build a Walmart" },
    { id: 335, text: "Michelle Obama's arms" },
    { id: 336, text: "Kim Jong-il" },
    { id: 337, text: "Battlefield amputations" },
    { id: 338, text: "A Mexican" },
    { id: 339, text: "Groping" },
    { id: 340, text: "A sad fat dragon with no friends" },
    { id: 341, text: "Betty White in the sack" },
    { id: 342, text: "Advice from a wise, old black man" },
    { id: 343, text: "Hunchbacks" },
    { id: 344, text: "Popsicle stick houses" },
    { id: 345, text: "Bullshit" },
    { id: 346, text: "Homeless people" },
    { id: 347, text: "Mathletes" },
    { id: 348, text: "New Age music" },
    { id: 349, text: "My son getting a grad degree in Romantics" },
    { id: 350, text: "Kim Kardashian" },
    { id: 351, text: "A bleached asshole" },
    { id: 352, text: "The South" },
    { id: 353, text: "An ugly face" },
    { id: 354, text: "Sunshine and rainbows" },
    { id: 355, text: "Being fat and stupid" },
    { id: 356, text: "Hitler" },
    { id: 357, text: "Vladimir Putin" },
    { id: 358, text: "The devil himself" },
    { id: 359, text: "Surprise military deployment" },
    { id: 360, text: "Same-sex ice dancing" },
    { id: 361, text: "A tiny horse" },
    { id: 362, text: "Justin Bieber" },
    { id: 363, text: "Homeless people" },
    { id: 364, text: "A murder most foul" },
    { id: 365, text: "Smegma" },
    { id: 366, text: "Losing one's train of thought mid-sentence" },
    { id: 367, text: "Centaurs" },
    { id: 368, text: "Chainsaws for hands" },
    { id: 369, text: "Having anuses for eyes" },
    { id: 370, text: "Judge Judy" },
    { id: 371, text: "Getting so angry that you pop a boner" },
    { id: 372, text: "Daddy issues" },
    { id: 373, text: "Waiting 'til marriage" },
    { id: 374, text: "A can of whoop-ass" },
    { id: 375, text: "Jibber-jabber" },
    { id: 376, text: "An endless stream of diarrhea" },
    { id: 377, text: "Eating the last known bison" },
    { id: 378, text: "Laying an egg" },
    { id: 379, text: "RoboCop" },
    { id: 380, text: "Peeing in a boner" },
    { id: 381, text: "A defective condom" },
    { id: 382, text: "Panty raids" },
    { id: 383, text: "Teen pregnancy" },
    { id: 384, text: "Whipping it out" },
    { id: 385, text: "Riding a donkey into the sunset" },
    { id: 386, text: "Figgy pudding" },
    { id: 387, text: "Hot people" },
    { id: 388, text: "My inner demons" },
    { id: 389, text: "A brain tumor" },
    { id: 390, text: "Having big dreams but no realistic way to achieve them" },
    { id: 391, text: "My Uber driver, Pavel" },
    { id: 392, text: "The bombing of Pearl Harbor" },
    { id: 393, text: "An asymmetric boob job" },
    { id: 394, text: "Guys who don't call" },
    { id: 395, text: "Seduction" },
    { id: 396, text: "Suicidal thoughts" },
    { id: 397, text: "A micropenis" },
    { id: 398, text: "The Kool-Aid Man" },
    { id: 399, text: "Slow motion replay" },
    { id: 400, text: "Mom" }
];
